version: '3.8'

services:
  frontend:
    container_name: ewastepas-courier-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:80" 
    networks:
      - ewastepas-bridge
    restart: unless-stopped

networks:
  ewastepas-bridge:
    external: true
